### ISSUE TITLE
wxPropertyGrid?

### ISSUE THREAD

**Issue by xsnakes** [wxphp/wxphp#106]
wxPropertyGrid - completed component?
Will be added wxPropertyGrid?

**Comment by jgmdev** [comment]
Since this component requires elements that use C++ templates/generics, it is going to be harder to automate the process of generating code that wraps it. 

Also I left a message (that may answer more deeply this issue) on wxphp site with some kind of status repor of projectt for those interested: 

http://wxphp.org/news/short-on-time
