### ISSUE TITLE
Trying to compile

### ISSUE THREAD

**Issue by kbhoward** [wxphp/wxphp#163]
Hey there,

Following comments/notes from Lord of The Rats and Dave.
I used git to clone and try to phpize....wants pkg.m4 in build folder.
So, i "touch" (create using touch cmd) it.
Phpize seems happier, complains now that it cant open pkg.m4 in current dir, but works none the less.
Configure works and is happy.
Make fails with an error about ';' expected before '}'
On line 645 of app.cpp, in function PHP_METHOD, there appears to be a missing semicolon....so i add it and 'make' again.
Seems good, as it gets farther but then dies with:
```
 app.cpp:135:27: error: 'call_user_function_ex' was not declared in this scope; did you mean 'call_user_function'?
  135 |         function_called = call_user_function_ex
```
Pissing in the wind here, as i'm not much of a dev, am using Debian Sid, and.....dont hate me....PHP 8.1....
Is anyone still playing with wxPHP or should I wipe myself off and just stop now?
Thanks in advance! ;)

**Comment by kbhoward** [comment]
@Rene
By the way, great suggestion using Docker....I'll give that a try too!
Again, thanks!

**Comment by LordOfTheRats** [comment]
Hi Howard,

I can't take much of the credit, that belongs to my predecessors for creating wxPHP and maintaining it for years. I just ported it to PHP7 (so I don't have to rewrite my codebase) more or less successfully :sweat_smile:. Maybe someday we will find someone with ample PHP extension experience who can tell me how to fix the memory management.

Docker is certainly useful for debugging compiling issues, since it can provide a clean build environment every time.
I just spun up a new container and mapped the wxphp project files into it to check the compilation issue
```bash
docker run --rm -it -v $PWD:/project ubuntu:jammy # use ubuntu:focal instead for Ubuntu 20.04 with PHP 7.4
```

Another great way for working with extensions is using [phpbrew](https://github.com/phpbrew/phpbrew). This allows the selection of a specific PHP version to work with.
```bash
# Install build dependencies, I hope that's everything
apt-get -qy install build-essential libxml2-dev libxslt1-dev libcurl4-openssl-dev libgtk2.0-dev libgconf2-dev libsdl1.2-dev libjpeg-dev libgtk-3-dev libwebkit2gtk-4.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libsqlite3-dev libbz2-dev 

# Install phpbrew to a convenient place
sudo curl -L -o /usr/local/bin/phpbrew https://github.com/phpbrew/phpbrew/raw/master/phpbrew
sudo chmod +x /usr/local/bin/phpbrew
phpbrew init
source ~/.phpbrew/bashrc # source bash support script into current shell

# Download and build PHP 7.4.3
phpbrew install 7.4.3 +neutral # add +debug to compile PHP with debugging support
phpbrew use php-7.4.3

# Download and build wxPHP
phpbrew ext install github:wxphp/wxphp -- --disable-wxphp-references-management # add --enable-wxwidgets-debug for wxphp debug output
```

Maybe this way you could get wxPHP going on Jammy.
