### ISSUE TITLE
wxProgressDialog::update

### ISSUE THREAD

**Issue by ulistaerk** [wxphp/wxphp#97]
Hi,

I'm experimenting with the wxDialog and noticed that it does not seem to extend wxGenericProgressDialog.
```php
$progresswnd = new wxProgressDialog( "title", "message", 100);

$progresswnd->ShowModal();
$progress = 0;
while($progress++ <= 100) { wxMilliSleep(100);
	$progresswnd->Update($progress, "Progress is $progress");
}
$progresswnd->Destroy();
```
This example creates the following error:

```
PHP Fatal error:  Wrong type or count of parameters passed to: wxWindow::Update
```

Greetings
Uli Stärk

**Comment by jgmdev** [comment]
It seems the the wxWindow::Update method is conflicting with wxGenericProgressDialog::Update. wxProgressDialog is extending wxGenericProgressDialog, just not that method as seen here: https://github.com/wxphp/wxphp/blob/master/includes/others.h#L1088. 

So this issue is related to something been wrong on the code generator. Which I will try to inspect now.

**Comment by jgmdev** [comment]
The commit also fixes many other methods with the same issue. Hopefully it doesn't brakes something else :P 

Here a sample code that now should work, since I noticed you where using ShowModal() which is blocking instead of Show().

```php
$progresswnd = new wxProgressDialog( "title", "message", 100);
$progresswnd->Show();

$progress = 0;
while($progress <= 100) 
{ 
    usleep(1000 * 200);
    $progresswnd->Update($progress, "Progress is $progress");
    $progress++;
}
```
